DROP TABLE IF EXISTS EMPLOYEE;
CREATE SEQUENCE EMPLOYEE_SEQ
  START WITH 1001
  INCREMENT BY 1
  MINVALUE 1001;

CREATE TABLE EMPLOYEE (
id INT AUTO_INCREMENT  PRIMARY KEY,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL
);

